name: graph
description: Graph datastructure
version: 0.0.1
author: Leon Fuß

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:

  uuid: ^3.0.0
  equatable: ^2.0.0-nullsafety.3

dev_dependencies:
  test: ^1.16.4
  pedantic: ^1.10.0

