name: graph
description: Graph representation on top of isar
version: 0.0.1
author: null
homepage: null

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.24.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.2
  some: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
